//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputersData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public int Id { get; set; }
        public int ComputerTypeId { get; set; }
        public string Vendor { get; set; }
        public string Model { get; set; }
        public int CPUId { get; set; }
        public int GPUId { get; set; }
        public int StorageDeviceId { get; set; }
        public string Memory { get; set; }
    
        public virtual ComputerType ComputerType { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual StorageDevice StorageDevice { get; set; }
    }
}
