//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int OriginCountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Pet Pet { get; set; }
        public virtual Product Product { get; set; }
    }
}
